---
- hosts: all
  tasks:
    - name: launch a Instance
      ec2:
         key_name: "{{ keypair }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ ap-south-1 }}"
         vpc_subnet_id: "{{ subnet }}"
         assign_public_ip: yes
      
