---
- hosts: all
  tasks:
    - name: launch a Instance
      ec2:
         key_name: "{{ keypair }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: subnet-4b3b4b23
         assign_public_ip: yes
      
